In [1]:
import tensorflow as tf
import numpy as np

In [2]:
xy = np.loadtxt('zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

X = tf.placeholder(tf.float32,[None,16])
Y = tf.placeholder(tf.int32, [None,1])

nb_classes = 7

#
# one hot Encodeing-> It'll expand the dimension
Y_one_hot = tf.one_hot(Y, nb_classes)

# Fix the dimension: Tensor's last dimension with "nb_classes" number of values
Y_one_hot = tf.reshape(Y_one_hot, [-1,nb_classes])

In [3]:
# Encoding results
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(Y_one_hot,feed_dict={X: x_data, Y: y_data}))

[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.

In [4]:
W = tf.Variable(tf.random_normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

softmax-> sigmoid의 matrix 확장판이다.  
이 함수를 통과한 모든 결과들은 0에서1 사이의 값을 가지고,  
모든 결과를 더하면 1이 되는 '확률' 성질을 가진다  

In [5]:
logits = tf.matmul(X,W)+b
hypothesis = tf.nn.softmax(logits)
loss_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels = Y_one_hot)
loss = tf.reduce_mean(loss_i)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(loss)

softmax의 결과에다가 가장큰 값의 index를 반환하는 argmax를 한 것과,  
onehot Encoding의 결과는 이론적으로 같게된다.  
이걸 이용해서 정확도를 구한다.

In [6]:
prediction = tf.argmax(hypothesis,1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [7]:
with tf.Session() as  sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            loss_val, acc_val = sess.run([loss,accuracy], feed_dict={X: x_data, Y: y_data})
            print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}".format(step, loss_val, acc_val))
    
    pred = sess.run(prediction, feed_dict={X: x_data})
    for p,y in zip(pred, y_data.flatten()):
        print("[{}] prediction: {} True Y: {}". format(p == int(y), p, int(y)))

Step:     0	Loss: 7.063	Acc: 3.96%
Step:   200	Loss: 0.480	Acc: 85.15%
Step:   400	Loss: 0.279	Acc: 92.08%
Step:   600	Loss: 0.196	Acc: 97.03%
Step:   800	Loss: 0.150	Acc: 97.03%
Step:  1000	Loss: 0.120	Acc: 99.01%
Step:  1200	Loss: 0.100	Acc: 99.01%
Step:  1400	Loss: 0.086	Acc: 100.00%
Step:  1600	Loss: 0.075	Acc: 100.00%
Step:  1800	Loss: 0.066	Acc: 100.00%
Step:  2000	Loss: 0.060	Acc: 100.00%
[True] prediction: 0 True Y: 0
[True] prediction: 0 True Y: 0
[True] prediction: 3 True Y: 3
[True] prediction: 0 True Y: 0
[True] prediction: 0 True Y: 0
[True] prediction: 0 True Y: 0
[True] prediction: 0 True Y: 0
[True] prediction: 3 True Y: 3
[True] prediction: 3 True Y: 3
[True] prediction: 0 True Y: 0
[True] prediction: 0 True Y: 0
[True] prediction: 1 True Y: 1
[True] prediction: 3 True Y: 3
[True] prediction: 6 True Y: 6
[True] prediction: 6 True Y: 6
[True] prediction: 6 True Y: 6
[True] prediction: 1 True Y: 1
[True] prediction: 0 True Y: 0
[True] prediction: 3 True Y: 3
[True] predi